### PR TITLE
Grammar and stylistic edits with revision tracking enabled

### PR DESCRIPTION
**Pull request by zhurin**

### CODE REVIEW

**Comment by zhurin** [comment]
Also, I was unclear about the OX1 command. What does it mean that the mode conflicts with the GPIB commands in that document?

**Comment by KIrill-ka** [comment]
> What does it mean that the mode conflicts with the GPIB commands in that document?

It attempts to talk to HP3478A on its own. So those GPIB commands will interfere with the commands sent via UART. It might be better to restrict UART commands in "extension mode", but I left them enabled for diagnostics/debugging purposes.

**Comment by zhurin** [comment]
OK, the way I interpreted it was that OX1 enabled the extensions, which are the commands described in the document, and OX0 disabled them so that only normal GPIB commands work. Currently, the document sounds like it's saying the opposite. Perhaps I'm misunderstanding something fundamental.

**Comment by zhurin** [comment]
Sounds good. Also, please re-read it to be sure I didn't accidentally change the meaning of something while editing.

**Pull request merged**
